import Head from "next/head";
import React from "react";

function Stats() {
  return (
    <React.Fragment>
      <Head>
        <title>Top NFTs | Miniso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Stats
    </React.Fragment>
  );
}

export default Stats;
