import Head from "next/head";
import React from "react";

function Create() {
  return (
    <React.Fragment>
      <Head>
        <title>Create NFTs | Miniso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Create
    </React.Fragment>
  );
}

export default Create;
