import Head from "next/head";
import React from "react";

function Explore() {

  return (
    <React.Fragment>
      {" "}
      <Head>
        <title>Explore collections | Miniso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Explore
    </React.Fragment>
  );
}

export default Explore;
