import Head from "next/head";
import React from "react";

function Dashboard() {
  return (
    <React.Fragment>
      <Head>
        <title>Dashboard | Miniso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Dashboard
    </React.Fragment>
  );
}

export default Dashboard;
